### ISSUE TITLE
cannot classify certain hashtags or keywords

### ISSUE THREAD

**Issue by stevemart** [IBM/cognitive-social-crm#28]
> I Got this email from an IBM'er who is running into some issues, opening it up as an issue.

First and foremost I would like to thank you very much for your great work to demonstrate Watson services in a CRM project.

I seem to be running into an issue when I change the hashtag or TWITTER_LISTEN_FOR value. 

These are the kind of errors I got from the console: 

1. 
```
at Function.ObserverMixin._notifyBaseObservers
(C:\Users\NoraAlNashwan\Downloads\cognitive\node_modules\loopback-datasource-juggler\lib\observer.js:178:5) 
[1] Unhandled error for request POST /auth/login: Error: login failed 
```

2.
```
Unhandled error for request GET /Analysis/sentimentSummary?access_token=zBQx7R5yKuBuO4K7NkHZWopoCdVaRTeypunJRoEfAee3J40uh3XNN6Qc9IMXWP19: Error: Authorization Required 
```

3. 
```
Unhandled error for request POST /auth/logout?access_token=zBQx7R5yKuBuO4K7NkHZWopoCdVaRTeypunJRoEfAee3J40uh3XNN6Qc9IMXWP19: Error: Value is not a string.
```

Note that I do not have a conversation workspace IDs because I do not care about conversation. 

Specifically I'm looking to see if it will work to show how Watson classifies Arabic tweets (sentiment in Natural Language Understanding).

**Comment by stevemart** [comment]
I followed up with the bug originator, she is able to get things working with `@aircanada` but she was hoping to get it working with `@STCcare` which tweets predominantly in Arabic.

**Comment by xnorax** [comment]
After updating twitter app, I got another error message.
`Unhandled error for request GET /Analysis/listByPostDate?access_token=&skip=0&limit=5: Error: read ECONNRESET`

**Comment by FMGordillo** [comment]
> After updating twitter app, I got another error message.
> `Unhandled error for request GET /Analysis/listByPostDate?access_token=&skip=0&limit=5: Error: read ECONNRESET`

@xnorax Aren´t you missing the access_token or the .env credentials?

**Comment by sanjeevghimire** [comment]
the new refactored code should cover this issue.
