### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by sangramrath** [IBM/cognitive-social-crm#35]
npm run setup fails with the below error:

> > social-crm-starter-demo-app@2.0.0 setup /xxxxxxx/cognitive-social-crm
> > node ./setup/social-crm-setup.js
> 
> /xxxxxxxx/cognitive-social-crm/server/utils/wsl-env.js:79
>           throw err
>           ^
> 
> SyntaxError: Unexpected token 
>  in JSON at position 483
>     at JSON.parse (<anonymous>)
>     at Object.sync.readJSON (/xxxxxxxx/cognitive-social-crm/node_modules/fs-sync/index.js:202:15)
>     at getJSONFile (/xxxxxxxxx/cognitive-social-crm/server/utils/wsl-env.js:43:23)
>     at init (/xxxxxxx/cognitive-social-crm/server/utils/wsl-env.js:62:34)
>     at /xxxxxxx/cognitive-social-crm/server/utils/wsl-env.js:168:3
>     at Object.<anonymous> (/xxxxxx/cognitive-social-crm/server/utils/wsl-env.js:243:2)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! social-crm-starter-demo-app@2.0.0 setup: `node ./setup/social-crm-setup.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the social-crm-starter-demo-app@2.0.0 setup script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /xxxxxx/.npm/_logs/2018-03-15T20_04_57_857Z-debug.log

npm@5.6.0
node@v8.10.0
OS: mac
angularcli installed

not sure if this is relevant and to do with the error but on running "npm install" I get the below message for node-gyp

> websocket@1.0.24 install /Users/sangram/Desktop/cloudworks/ibm/ai/tsa/cognitive-social-crm/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

**Comment by scottdangelo** [comment]
I was not able to reproduce this. I used a fresh setup and was able to run the `npm run setup` successfully.
I don't believe the error is a result of your "npm install" error.
Instead, it looks like a json parsing issue.
First, the json for `vcap-local.json` is used. You should not have changed this, but running 'git checkout vcap-local.json` should return it to the state in the repository.
Then, the json in `env-vars.json` is examined. If I were you, I'd look at that file and see if there is a syntax error.
You could try pasting the contents of the file in a [json format checker]
(https://jsonformatter.curiousconcept.com/) to see if that helps locate the issue.

**Comment by scottdangelo** [comment]
Not able to reproduce and no response from original issue reporter.
