### ISSUE TITLE
fails with Python 3

### ISSUE THREAD

**Issue by markstur** [IBM/cognitive-social-crm#44]
Yeah, I didn't think it was a Python project either, but if your default python is 3.x, you won't be able to run "npm install" because the client build uses gyp and expects Python 2.x.

I guess the workaround is to have a python2.7 (so you need some non-default py 2.7 installed) and then:

   python2.7 -m pip install --user virtualenv
   python2.7 -m virtualenv .venv
   source .venv/bin/activate

Now you are in a virtualenv using your python2.7 as the default python.
Run npm install.
Run "deactivate" to leave the virtual environment.

**Comment by stevemart** [comment]
Closing as @sanjeevghimire ran this with py3.6
