### ISSUE TITLE
Running on IBM Cloud fails

### ISSUE THREAD

**Issue by alexandersandstrom** [IBM/cognitive-social-crm#55]
I'm unable to get the server running on IBM cloud. I've pushed code successfully, and changed environment variables, but the app fails to start. In the IBM Cloud app logs I get the following:

> September 12th 2018, 15:56:15.603 | Cell 07152278-7679-45e0-8721-13fcb1d59aa0 successfully destroyed container for instance 5c48e6da-0ce0-4294-5409-a5bc | CELL
-- | -- | --
  | September 12th 2018, 15:56:13.281 | Cell 07152278-7679-45e0-8721-13fcb1d59aa0 destroying container for instance 5c48e6da-0ce0-4294-5409-a5bc | CELL
  | September 12th 2018, 15:56:13.281 | Cell 07152278-7679-45e0-8721-13fcb1d59aa0 stopping instance 5c48e6da-0ce0-4294-5409-a5bc | CELL
  | September 12th 2018, 15:56:13.281 | Exit status 0 | CELL/SSHD
  | September 12th 2018, 15:56:13.050 | Exit status 137 | PROXY
  | September 12th 2018, 15:56:13.039 | Exit status 1 | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR! A complete log of this run can be found in: | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR! Exit status 1 | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR! | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR! server@1.0.0 start:prod: `node ./node_modules/typescript/lib/tsc && NODE_ENV=production node dist/server.js` | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above. | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR! Failed at the server@1.0.0 start:prod script. | APP/PROC/WEB
  | September 12th 2018, 15:56:13.038 | npm ERR!     /home/vcap/app/.npm/_logs/2018-09-12T13_56_11_907Z-debug.log | APP/PROC/WEB
  | September 12th 2018, 15:56:13.037 | npm ERR! errno 1 | APP/PROC/WEB
  | September 12th 2018, 15:56:13.034 | npm ERR! code ELIFECYCLE | APP/PROC/WEB
  | September 12th 2018, 15:56:13.033 | at Function.Module._resolveFilename (module.js:547:15) | APP/PROC/WEB
  | September 12th 2018, 15:56:13.033 | at Function.Module.runMain (module.js:693:10) | APP/PROC/WEB
  | September 12th 2018, 15:56:13.033 | Error: Cannot find module '/home/vcap/app/node_modules/typescript/lib/tsc' | APP/PROC/WEB
  | September 12th 2018, 15:56:13.033 | at startup (bootstrap_node.js:191:16) | APP/PROC/WEB
  | September 12th 2018, 15:56:13.033 | at Function.Module._load (module.js:474:25) | APP/PROC/WEB
  | September 12th 2018, 15:56:13.033 | at bootstrap_node.js:612:3 | APP/PROC/WEB
  | September 12th 2018, 15:56:13.032 | throw err; | APP/PROC/WEB
  | September 12th 2018, 15:56:13.032 | ^ | APP/PROC/WEB
  | September 12th 2018, 15:56:12.687 | Process has crashed with type: "web" | API
  | September 12th 2018, 15:56:12.687 | App instance exited with guid ea6fbec6-9188-4849-9d4c-d862093fe45d payload: {"instance"=>"5c48e6da-0ce0-4294-5409-a5bc", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>11, "crash_timestamp"=>1536760572052118202, "version"=>"d4ec4fb4-f31d-4915-9192-c5f3499d8754"} | API
  | September 12th 2018, 15:56:12.012 | module.js:549 | APP/PROC/WEB
  | September 12th 2018, 15:56:11.375 | > server@1.0.0 start:prod /home/vcap/app | APP/PROC/WEB
  | September 12th 2018, 15:56:11.344 | > node ./node_modules/typescript/lib/tsc && NODE_ENV=production node dist/server.js | APP/PROC/WEB
  | September 12th 2018, 15:56:00.709 | Starting health monitoring of container | CELL
  | September 12th 2018, 15:55:54.343 | Cell 07152278-7679-45e0-8721-13fcb1d59aa0 successfully created container for instance 5c48e6da-0ce0-4294-5409-a5bc | CELL
  | September 12th 2018, 15:55:53.047 | Cell 07152278-7679-45e0-8721-13fcb1d59aa0 creating container for instance 5c48e6da-0ce0-4294-5409-a5bc | CELL

Running it locally works well in dev mode ("npm run start"), but fails in production mode ("npm run start:prod" in server directory). Not sure if the two problems are related or not. Starting the server in production mode gives a bunch of errors like this:

> error TS5055: Cannot write file 'XYZ/cognitive-social-crm/server/dist/dist/server.js' because it would overwrite input file.

and then ending just like when trying in IBM cloud:

> npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start:prod: `node ./node_modules/typescript/lib/tsc && NODE_ENV=production node dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexander/.npm/_logs/2018-09-12T12_55_22_242Z-debug.log

Any ideas what might be wrong? I tried to follow the readme instructions, but guess I might have missed out on something unless there is an issue with the current code version.

**Comment by sanjeevghimire** [comment]
@alexandersandstrom checking.... looks like its not finding `tsc` that compiles type script. I will let you know what could have gone wrong.
