### ISSUE TITLE
npm run app-install

### ISSUE THREAD

**Issue by bryan-ninjamoba** [IBM/cognitive-social-crm#63]
I get these errors installing dependencies on a windows 10 machine with current installs -? Any insights welcome

PS C:\Users\Owner\cognitive-social-crm> npm run app-install

> cognitive-social-crm@1.0.0 app-install C:\Users\Owner\cognitive-social-crm
> npm install && npm run install:client && npm run install:server

npm WARN cognitive-social-crm@1.0.0 No repository field.

added 42 packages from 32 contributors and audited 48 packages in 2.168s
found 0 vulnerabilities

> cognitive-social-crm@1.0.0 preinstall:client C:\Users\Owner\cognitive-social-crm
> cd client && rm -rf dist

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognitive-social-crm@1.0.0 preinstall:client: `cd client && rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognitive-social-crm@1.0.0 preinstall:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-11-26T14_52_33_983Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognitive-social-crm@1.0.0 app-install: `npm install && npm run install:client && npm run install:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognitive-social-crm@1.0.0 app-install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-11-26T14_52_34_008Z-debug.log

**Comment by stevemart** [comment]
Hi @bryan-ninjamoba currently Windows OS is not supported and not on our roadmap of things to address with this repo.
