### ISSUE TITLE
Need update of Cognitive-social-crm help steps

### ISSUE THREAD

**Issue by bryan-ninjamoba** [IBM/cognitive-social-crm#68]

**Comment by stevemart** [comment]
Hi @bryan-ninjamoba -- is there a specific step that you feel needs updating?

**Comment by bryan-ninjamoba** [comment]
> Hi @bryan-ninjamoba -- is there a specific step that you feel needs updating?

5 Import the Assistant workspace

and

6. Configure credentials

**Comment by bryan-ninjamoba** [comment]
additionally is this creation of application step missing? what is this step referring to?

"Use the name of the application you created previously to update the configuration files locally.

Open the manifest.yml file and change the name value to the **unique application name you created on IBM Cloud previously.**"

**Comment by bryan-ninjamoba** [comment]
Ive gotten the project to run locally (through a gauntlet of trial and error) but although it rendered on the ibmcloud it doesnt seem to function there.. ALSO very oddly the tweets from the original writer are being displayed...LOOK AT THIS SCREEN SHOT OF MY LOCAL BUILD?!?!?!? Im getting the feeling the repo is bogus. What is the actual point for the twitter app configuration listener?  why do these old tweets show up unless they are just in the json used to emulate a training of the watson config. I hope you can prove me wrong.

https://screenshotscdn.firefoxusercontent.com/images/ed3a9d10-838c-4efa-87b2-213652617c27.png
![ed3a9d10-838c-4efa-87b2-213652617c27 1](https://user-images.githubusercontent.com/40713372/51262862-7c7e4080-19b3-11e9-9330-8c8269924128.png)

**Comment by stevemart** [comment]
@bryan-ninjamoba definitely not bogus :) sample data/tweets are loaded to ensure the UI is displaying meaningful information when debugging or loading the app for the first time. They're over here: https://github.com/IBM/cognitive-social-crm/blob/master/server/src/data/SampleTweets.ts -- you're not seeing tweets from the original author.

@sanjeevghimire will spend some time on this one today and tomorrow to ensure the app is working as expected and is in-fact reading new tweets as they come (note there is about a 5 minute lag between a tweet and seeing it on the dashboard). We'll also refresh the documentation to ensure it reads more clearly. 

Thanks for the feedback, if you're comfortable submitting PRs then I encourage you to help flesh out the README in spots you felt were lacking so others won't stumble on the same parts.

**Comment by sanjeevghimire** [comment]
@bryan-ninjamoba I am looking into this. I will be re running all the steps and make changes to the instructions as needed to make it clearer. Thanks for the valuable feedback.

**Comment by sanjeevghimire** [comment]
@bryan-ninjamoba  I have update the readme and also made the push to cloud simpler. Please take a look when you have time.

**Comment by stevemart** [comment]
@bryan-ninjamoba we're closing this one out for now. @sanjeevghimire made changes in https://github.com/IBM/cognitive-social-crm/commit/511eaf6eaec7f78e2a78e727412b8d70824ccce7 and your problem should be resolved. Please re-open if you're still running into issues.
